---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: retro-board
  name: retro-board-company-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  namespace: retro-board
  labels:
    name: company-service
    app: company-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
        name: company-service
    spec:
      serviceAccountName: retro-board-company-service
      imagePullSecrets:
        - name: regcred
      containers:
        - name: company-service
          image: containers.chewedfeed.com/retro-board/company-service:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-vault-token
                  key: token
            - name: OWNER_ROLE
              value: "company_owner"
            - name: LEADER_ROLE
              value: "retro_leader"
            - name: USER_ROLE
              value: "retro_user"
            - name: RDS_DB
              value: "retroboard"
            - name: CLUSTER_ISSUER
              value: "acme-prod"
            - name: RDS_HOSTNAME
              value: "kube-nas.home.develbox.info"
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: retro-board
  labels:
    app: company-service
    name: company-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: company-service
